/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderPostItems', 'model/OrderPostShipping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderPostItems'), require('./OrderPostShipping'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.OrderPost = factory(root.PicanovaApi.ApiClient, root.PicanovaApi.OrderPostItems, root.PicanovaApi.OrderPostShipping);
  }
}(this, function(ApiClient, OrderPostItems, OrderPostShipping) {
  'use strict';




  /**
   * The OrderPost model module.
   * @module model/OrderPost
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderPost</code>.
   * @alias module:model/OrderPost
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>OrderPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderPost} obj Optional instance to populate.
   * @return {module:model/OrderPost} The populated <code>OrderPost</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('is_test')) {
        obj['is_test'] = ApiClient.convertToType(data['is_test'], 'Boolean');
      }
      if (data.hasOwnProperty('shipping_method')) {
        obj['shipping_method'] = ApiClient.convertToType(data['shipping_method'], 'String');
      }
      if (data.hasOwnProperty('customs_shipping_costs')) {
        obj['customs_shipping_costs'] = ApiClient.convertToType(data['customs_shipping_costs'], 'Number');
      }
      if (data.hasOwnProperty('shipping')) {
        obj['shipping'] = OrderPostShipping.constructFromObject(data['shipping']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [OrderPostItems]);
      }
    }
    return obj;
  }

  /**
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * @member {Boolean} is_test
   */
  exports.prototype['is_test'] = undefined;
  /**
   * @member {String} shipping_method
   */
  exports.prototype['shipping_method'] = undefined;
  /**
   * Used to print the customs duty value of the order item and shipping costs shown on the customs duty invoice
   * @member {Number} customs_shipping_costs
   */
  exports.prototype['customs_shipping_costs'] = undefined;
  /**
   * @member {module:model/OrderPostShipping} shipping
   */
  exports.prototype['shipping'] = undefined;
  /**
   * @member {Array.<module:model/OrderPostItems>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


