/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.OrderPostOptions = factory(root.PicanovaApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OrderPostOptions model module.
   * @module model/OrderPostOptions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderPostOptions</code>.
   * @alias module:model/OrderPostOptions
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>OrderPostOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderPostOptions} obj Optional instance to populate.
   * @return {module:model/OrderPostOptions} The populated <code>OrderPostOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('1')) {
        obj['1'] = ApiClient.convertToType(data['1'], 'Number');
      }
      if (data.hasOwnProperty('5')) {
        obj['5'] = ApiClient.convertToType(data['5'], 'Number');
      }
      if (data.hasOwnProperty('Stretcher frame')) {
        obj['Stretcher frame'] = ApiClient.convertToType(data['Stretcher frame'], 'String');
      }
      if (data.hasOwnProperty('Easel Back')) {
        obj['Easel Back'] = ApiClient.convertToType(data['Easel Back'], 'String');
      }
    }
    return obj;
  }

  /**
   * 'key' is the option's id, 'value' is the option's value id
   * @member {Number} 1
   */
  exports.prototype['1'] = undefined;
  /**
   * 'key' is the option's id, 'value' is the option's value id
   * @member {Number} 5
   */
  exports.prototype['5'] = undefined;
  /**
   * Here the 'key' is the option's name, 'value' is the option's value name
   * @member {String} Stretcher frame
   */
  exports.prototype['Stretcher frame'] = undefined;
  /**
   * Here the 'key' is the option's name, 'value' is the option's value name
   * @member {String} Easel Back
   */
  exports.prototype['Easel Back'] = undefined;



  return exports;
}));


