/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.OrderPostShipping = factory(root.PicanovaApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OrderPostShipping model module.
   * @module model/OrderPostShipping
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderPostShipping</code>.
   * @alias module:model/OrderPostShipping
   * @class
   * @param firstname {String} 
   * @param lastname {String} 
   * @param streetPrimary {String} 
   * @param city {String} 
   * @param postcode {String} 
   * @param countryId {Number} 
   */
  var exports = function(firstname, lastname, streetPrimary, city, postcode, countryId) {
    var _this = this;


    _this['firstname'] = firstname;
    _this['lastname'] = lastname;

    _this['street_primary'] = streetPrimary;

    _this['city'] = city;
    _this['postcode'] = postcode;
    _this['country_id'] = countryId;


  };

  /**
   * Constructs a <code>OrderPostShipping</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderPostShipping} obj Optional instance to populate.
   * @return {module:model/OrderPostShipping} The populated <code>OrderPostShipping</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('street_primary')) {
        obj['street_primary'] = ApiClient.convertToType(data['street_primary'], 'String');
      }
      if (data.hasOwnProperty('street_secondary')) {
        obj['street_secondary'] = ApiClient.convertToType(data['street_secondary'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('postcode')) {
        obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
      }
      if (data.hasOwnProperty('country_id')) {
        obj['country_id'] = ApiClient.convertToType(data['country_id'], 'Number');
      }
      if (data.hasOwnProperty('region_id')) {
        obj['region_id'] = ApiClient.convertToType(data['region_id'], 'Number');
      }
      if (data.hasOwnProperty('telephone')) {
        obj['telephone'] = ApiClient.convertToType(data['telephone'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {String} street_primary
   */
  exports.prototype['street_primary'] = undefined;
  /**
   * @member {String} street_secondary
   */
  exports.prototype['street_secondary'] = undefined;
  /**
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} postcode
   */
  exports.prototype['postcode'] = undefined;
  /**
   * @member {Number} country_id
   */
  exports.prototype['country_id'] = undefined;
  /**
   * @member {Number} region_id
   */
  exports.prototype['region_id'] = undefined;
  /**
   * @member {String} telephone
   */
  exports.prototype['telephone'] = undefined;



  return exports;
}));


