/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderPostOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderPostOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.OrderPostItems = factory(root.PicanovaApi.ApiClient, root.PicanovaApi.OrderPostOptions);
  }
}(this, function(ApiClient, OrderPostOptions) {
  'use strict';




  /**
   * The OrderPostItems model module.
   * @module model/OrderPostItems
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderPostItems</code>.
   * @alias module:model/OrderPostItems
   * @class
   * @param quantity {Number} 
   * @param variantCode {String} 
   * @param file {String} 
   */
  var exports = function(quantity, variantCode, file) {
    var _this = this;

    _this['quantity'] = quantity;
    _this['variant_code'] = variantCode;

    _this['file'] = file;

  };

  /**
   * Constructs a <code>OrderPostItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderPostItems} obj Optional instance to populate.
   * @return {module:model/OrderPostItems} The populated <code>OrderPostItems</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('variant_code')) {
        obj['variant_code'] = ApiClient.convertToType(data['variant_code'], 'String');
      }
      if (data.hasOwnProperty('custom_value')) {
        obj['custom_value'] = ApiClient.convertToType(data['custom_value'], 'Number');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = OrderPostOptions.constructFromObject(data['options']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * @member {String} variant_code
   */
  exports.prototype['variant_code'] = undefined;
  /**
   * Used to print the customs duty value of the order item and shipping costs shown on the customs duty invoice
   * @member {Number} custom_value
   */
  exports.prototype['custom_value'] = undefined;
  /**
   * @member {String} file
   */
  exports.prototype['file'] = undefined;
  /**
   * @member {module:model/OrderPostOptions} options
   */
  exports.prototype['options'] = undefined;



  return exports;
}));


