/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ShippingItem', 'model/ShippingPostShipping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ShippingItem'), require('./ShippingPostShipping'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.ShippingPost = factory(root.PicanovaApi.ApiClient, root.PicanovaApi.ShippingItem, root.PicanovaApi.ShippingPostShipping);
  }
}(this, function(ApiClient, ShippingItem, ShippingPostShipping) {
  'use strict';




  /**
   * The ShippingPost model module.
   * @module model/ShippingPost
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShippingPost</code>.
   * @alias module:model/ShippingPost
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ShippingPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShippingPost} obj Optional instance to populate.
   * @return {module:model/ShippingPost} The populated <code>ShippingPost</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('shipping')) {
        obj['shipping'] = ShippingPostShipping.constructFromObject(data['shipping']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [ShippingItem]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ShippingPostShipping} shipping
   */
  exports.prototype['shipping'] = undefined;
  /**
   * @member {Array.<module:model/ShippingItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


