/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.ShippingItem = factory(root.PicanovaApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ShippingItem model module.
   * @module model/ShippingItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShippingItem</code>.
   * @alias module:model/ShippingItem
   * @class
   * @param quantity {Number} 
   * @param variantId {Number} Please use /beta/products/{product_id} to get a certain product variant id
   */
  var exports = function(quantity, variantId) {
    var _this = this;

    _this['quantity'] = quantity;
    _this['variant_id'] = variantId;
  };

  /**
   * Constructs a <code>ShippingItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShippingItem} obj Optional instance to populate.
   * @return {module:model/ShippingItem} The populated <code>ShippingItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('variant_id')) {
        obj['variant_id'] = ApiClient.convertToType(data['variant_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * Please use /beta/products/{product_id} to get a certain product variant id
   * @member {Number} variant_id
   */
  exports.prototype['variant_id'] = undefined;



  return exports;
}));


