/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleOrderPriceDetails', 'model/SingleOrderTotalsCustomsShippingCostsDetails', 'model/SingleOrderTotalsShippingAmountDetails', 'model/SingleOrderTotalsTotalAmountDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SingleOrderPriceDetails'), require('./SingleOrderTotalsCustomsShippingCostsDetails'), require('./SingleOrderTotalsShippingAmountDetails'), require('./SingleOrderTotalsTotalAmountDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.SingleOrderTotals = factory(root.PicanovaApi.ApiClient, root.PicanovaApi.SingleOrderPriceDetails, root.PicanovaApi.SingleOrderTotalsCustomsShippingCostsDetails, root.PicanovaApi.SingleOrderTotalsShippingAmountDetails, root.PicanovaApi.SingleOrderTotalsTotalAmountDetails);
  }
}(this, function(ApiClient, SingleOrderPriceDetails, SingleOrderTotalsCustomsShippingCostsDetails, SingleOrderTotalsShippingAmountDetails, SingleOrderTotalsTotalAmountDetails) {
  'use strict';




  /**
   * The SingleOrderTotals model module.
   * @module model/SingleOrderTotals
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SingleOrderTotals</code>.
   * @alias module:model/SingleOrderTotals
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SingleOrderTotals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SingleOrderTotals} obj Optional instance to populate.
   * @return {module:model/SingleOrderTotals} The populated <code>SingleOrderTotals</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('subtotal_amount')) {
        obj['subtotal_amount'] = ApiClient.convertToType(data['subtotal_amount'], 'Number');
      }
      if (data.hasOwnProperty('subtotal_amount_details')) {
        obj['subtotal_amount_details'] = SingleOrderPriceDetails.constructFromObject(data['subtotal_amount_details']);
      }
      if (data.hasOwnProperty('shipping_amount')) {
        obj['shipping_amount'] = ApiClient.convertToType(data['shipping_amount'], 'Number');
      }
      if (data.hasOwnProperty('shipping_amount_details')) {
        obj['shipping_amount_details'] = SingleOrderTotalsShippingAmountDetails.constructFromObject(data['shipping_amount_details']);
      }
      if (data.hasOwnProperty('total_amount')) {
        obj['total_amount'] = ApiClient.convertToType(data['total_amount'], 'Number');
      }
      if (data.hasOwnProperty('total_amount_details')) {
        obj['total_amount_details'] = SingleOrderTotalsTotalAmountDetails.constructFromObject(data['total_amount_details']);
      }
      if (data.hasOwnProperty('customs_shipping_costs')) {
        obj['customs_shipping_costs'] = ApiClient.convertToType(data['customs_shipping_costs'], 'Number');
      }
      if (data.hasOwnProperty('customs_shipping_costs_details')) {
        obj['customs_shipping_costs_details'] = SingleOrderTotalsCustomsShippingCostsDetails.constructFromObject(data['customs_shipping_costs_details']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} subtotal_amount
   */
  exports.prototype['subtotal_amount'] = undefined;
  /**
   * @member {module:model/SingleOrderPriceDetails} subtotal_amount_details
   */
  exports.prototype['subtotal_amount_details'] = undefined;
  /**
   * @member {Number} shipping_amount
   */
  exports.prototype['shipping_amount'] = undefined;
  /**
   * @member {module:model/SingleOrderTotalsShippingAmountDetails} shipping_amount_details
   */
  exports.prototype['shipping_amount_details'] = undefined;
  /**
   * @member {Number} total_amount
   */
  exports.prototype['total_amount'] = undefined;
  /**
   * @member {module:model/SingleOrderTotalsTotalAmountDetails} total_amount_details
   */
  exports.prototype['total_amount_details'] = undefined;
  /**
   * @member {Number} customs_shipping_costs
   */
  exports.prototype['customs_shipping_costs'] = undefined;
  /**
   * @member {module:model/SingleOrderTotalsCustomsShippingCostsDetails} customs_shipping_costs_details
   */
  exports.prototype['customs_shipping_costs_details'] = undefined;



  return exports;
}));


