/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleOrderCreatedAt', 'model/SingleOrderItems', 'model/SingleOrderShippingMethod', 'model/SingleOrderTotals'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SingleOrderCreatedAt'), require('./SingleOrderItems'), require('./SingleOrderShippingMethod'), require('./SingleOrderTotals'));
  } else {
    // Browser globals (root is window)
    if (!root.PicanovaApi) {
      root.PicanovaApi = {};
    }
    root.PicanovaApi.SingleOrder = factory(root.PicanovaApi.ApiClient, root.PicanovaApi.SingleOrderCreatedAt, root.PicanovaApi.SingleOrderItems, root.PicanovaApi.SingleOrderShippingMethod, root.PicanovaApi.SingleOrderTotals);
  }
}(this, function(ApiClient, SingleOrderCreatedAt, SingleOrderItems, SingleOrderShippingMethod, SingleOrderTotals) {
  'use strict';




  /**
   * The SingleOrder model module.
   * @module model/SingleOrder
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SingleOrder</code>.
   * @alias module:model/SingleOrder
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>SingleOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SingleOrder} obj Optional instance to populate.
   * @return {module:model/SingleOrder} The populated <code>SingleOrder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('is_test')) {
        obj['is_test'] = ApiClient.convertToType(data['is_test'], 'Boolean');
      }
      if (data.hasOwnProperty('shipping_method')) {
        obj['shipping_method'] = SingleOrderShippingMethod.constructFromObject(data['shipping_method']);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('status_label')) {
        obj['status_label'] = ApiClient.convertToType(data['status_label'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = SingleOrderCreatedAt.constructFromObject(data['created_at']);
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = SingleOrderCreatedAt.constructFromObject(data['updated_at']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [SingleOrderItems]);
      }
      if (data.hasOwnProperty('totals')) {
        obj['totals'] = SingleOrderTotals.constructFromObject(data['totals']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * @member {Boolean} is_test
   */
  exports.prototype['is_test'] = undefined;
  /**
   * @member {module:model/SingleOrderShippingMethod} shipping_method
   */
  exports.prototype['shipping_method'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} status_label
   */
  exports.prototype['status_label'] = undefined;
  /**
   * @member {module:model/SingleOrderCreatedAt} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {module:model/SingleOrderCreatedAt} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {Array.<module:model/SingleOrderItems>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {module:model/SingleOrderTotals} totals
   */
  exports.prototype['totals'] = undefined;



  return exports;
}));


