/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PicanovaApi);
  }
}(this, function(expect, PicanovaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PicanovaApi.InlineResponse2006Data();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2006Data', function() {
    it('should create an instance of InlineResponse2006Data', function() {
      // uncomment below and update the code to test InlineResponse2006Data
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be.a(PicanovaApi.InlineResponse2006Data);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property variantId (base name: "variant_id")', function() {
      // uncomment below and update the code to test the property variantId
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property variantCode (base name: "variant_code")', function() {
      // uncomment below and update the code to test the property variantCode
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property printfile (base name: "printfile")', function() {
      // uncomment below and update the code to test the property printfile
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property priceDetails (base name: "price_details")', function() {
      // uncomment below and update the code to test the property priceDetails
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property shippingCountries (base name: "shipping_countries")', function() {
      // uncomment below and update the code to test the property shippingCountries
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new PicanovaApi.InlineResponse2006Data();
      //expect(instance).to.be();
    });

  });

}));
