/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PicanovaApi);
  }
}(this, function(expect, PicanovaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PicanovaApi.OrderPostOptions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderPostOptions', function() {
    it('should create an instance of OrderPostOptions', function() {
      // uncomment below and update the code to test OrderPostOptions
      //var instance = new PicanovaApi.OrderPostOptions();
      //expect(instance).to.be.a(PicanovaApi.OrderPostOptions);
    });

    it('should have the property _1 (base name: "1")', function() {
      // uncomment below and update the code to test the property _1
      //var instance = new PicanovaApi.OrderPostOptions();
      //expect(instance).to.be();
    });

    it('should have the property _5 (base name: "5")', function() {
      // uncomment below and update the code to test the property _5
      //var instance = new PicanovaApi.OrderPostOptions();
      //expect(instance).to.be();
    });

    it('should have the property stretcherFrame (base name: "Stretcher frame")', function() {
      // uncomment below and update the code to test the property stretcherFrame
      //var instance = new PicanovaApi.OrderPostOptions();
      //expect(instance).to.be();
    });

    it('should have the property easelBack (base name: "Easel Back")', function() {
      // uncomment below and update the code to test the property easelBack
      //var instance = new PicanovaApi.OrderPostOptions();
      //expect(instance).to.be();
    });

  });

}));
