/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PicanovaApi);
  }
}(this, function(expect, PicanovaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PicanovaApi.OrderPost();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderPost', function() {
    it('should create an instance of OrderPost', function() {
      // uncomment below and update the code to test OrderPost
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be.a(PicanovaApi.OrderPost);
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

    it('should have the property isTest (base name: "is_test")', function() {
      // uncomment below and update the code to test the property isTest
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

    it('should have the property shippingMethod (base name: "shipping_method")', function() {
      // uncomment below and update the code to test the property shippingMethod
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

    it('should have the property customsShippingCosts (base name: "customs_shipping_costs")', function() {
      // uncomment below and update the code to test the property customsShippingCosts
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

    it('should have the property shipping (base name: "shipping")', function() {
      // uncomment below and update the code to test the property shipping
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instance = new PicanovaApi.OrderPost();
      //expect(instance).to.be();
    });

  });

}));
