/**
 * Picanova API
 * Picanova API documentation
 *
 * OpenAPI spec version: 
 * Contact: apirequest@picanova.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PicanovaApi);
  }
}(this, function(expect, PicanovaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PicanovaApi.SingleOrderTotals();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SingleOrderTotals', function() {
    it('should create an instance of SingleOrderTotals', function() {
      // uncomment below and update the code to test SingleOrderTotals
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be.a(PicanovaApi.SingleOrderTotals);
    });

    it('should have the property subtotalAmount (base name: "subtotal_amount")', function() {
      // uncomment below and update the code to test the property subtotalAmount
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property subtotalAmountDetails (base name: "subtotal_amount_details")', function() {
      // uncomment below and update the code to test the property subtotalAmountDetails
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property shippingAmount (base name: "shipping_amount")', function() {
      // uncomment below and update the code to test the property shippingAmount
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property shippingAmountDetails (base name: "shipping_amount_details")', function() {
      // uncomment below and update the code to test the property shippingAmountDetails
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "total_amount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property totalAmountDetails (base name: "total_amount_details")', function() {
      // uncomment below and update the code to test the property totalAmountDetails
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property customsShippingCosts (base name: "customs_shipping_costs")', function() {
      // uncomment below and update the code to test the property customsShippingCosts
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

    it('should have the property customsShippingCostsDetails (base name: "customs_shipping_costs_details")', function() {
      // uncomment below and update the code to test the property customsShippingCostsDetails
      //var instance = new PicanovaApi.SingleOrderTotals();
      //expect(instance).to.be();
    });

  });

}));
